
from pathlib import Path 
import sys, os
sys.path.insert(1, os.path.abspath('../') )

DATA_PROCESSED = Path('data/processed')
DATA_PREPROCESSED = Path('data/preprocessed')
DATA_RAW = Path('data/raw') #'/proj/marine/users/x_bensc/NEMOGCM/tests/BASIN_compiled_v0.1.2/'

time_start = 0
time_stop   = 30
n_chunks = 4

if abs(time_start-time_stop)%n_chunks==0:
    n_steps = int(abs(time_start-time_stop)/n_chunks)
else:
    n_steps = int(abs(time_start-time_stop)/n_chunks)+1
timestep_chunks = [f'{i*n_steps}_{(i+1)*n_steps}' if (i+1)*n_steps<time_stop else f'{i*n_steps}_{time_stop}' for i in range(n_chunks)]

files_in_raw = [i.name for i in list((DATA_RAW / 'EXP00_test' ).glob('*grid*.nc'))]
#ALL_EXPS = [i.name for i in list(Path('data/raw/').glob('*'))]

#variables = 

rule create_figure_spinup:
    input: 
        expand(
            DATA_PROCESSED / '{{exp}}' / '{{exp}}_{ts_te}.nc',
            ts_te = timestep_chunks
    )
    output:
        'figures/{exp}/spinup.pdf'
    shell:
        'touch {output}'


rule create_config:
    input:
        'configs/base.yml'
    output:
        'configs/{exp}/base.yml',
        'configs/{exp}/subconfig_{exp}.yml'
    run:
        from ECO.utils import config_preparation
        config_preparation(exp=wildcards.exp,time_start=time_start,time_stop=time_stop,n_chunks=n_chunks)

rule preprocess:
    input: 
        expand(
        DATA_RAW / '{{exp}}' / '{files}',
        files = files_in_raw
        ),
        'configs/{exp}/base.yml',
        'configs/{exp}/subconfig_{exp}.yml'
    output:
        expand(
            DATA_PREPROCESSED / '{{exp}}' / '{{exp}}_{ts_te}.nc',
            ts_te = timestep_chunks
        )
    shell:
        'python ECO/processing/ECO_processing.py -p configs/{wildcards.exp} -c subconfig_{wildcards.exp} -m preprocess'

rule process:
    input: 
        expand(
        DATA_PREPROCESSED / '{{exp}}' / '{{exp}}_{ts_te}.nc',
        ts_te = timestep_chunks
        ),
        'configs/{exp}/base.yml',
        'configs/{exp}/subconfig_{exp}.yml'
    output:
        expand(
            DATA_PROCESSED / '{{exp}}' / '{{exp}}_{ts_te}.nc',
            ts_te = timestep_chunks
        )
    shell:
        'python ECO/processing/ECO_processing.py -p configs/{wildcards.exp} -c subconfig_{wildcards.exp}'