preprocessing:
  prioritize_existing: true
processing:
  exp_in: EXP02_1m500
  exp_out: EXP02
  exp_out_suffix: _1m500
  n_chunks: 10
  time_start: 0
  time_stop: 6000
  nemo_path: data/raw/EXP02
  domain_path: data/raw/EXP02
  dynamics: false
