preprocessing:
  prioritize_existing: true
processing:
  domain_path: data/raw/EXP02
  dynamics: false
  exp_in: EXP02_rest6m2000
  exp_out: EXP02
  exp_out_suffix: _rest6m2000
  n_chunks: 10
  nemo_path: data/raw/EXP02
  time_start: 0
  time_stop: 4100
