preprocessing:
  prioritize_existing: true
processing:
  exp_in: EXP00_test
  exp_out: EXP00_test
  nemo_path      : data/raw
  domain_path    : data/raw
  n_chunks: 4
  time_start: 0
  time_stop: 30

