preprocessing:
  prioritize_existing: true
  
  vars_to_pass:      # Key is the variables original name, value the new name
        mldr10_1: mld
        zos     : zos
        so      : so
        thetao  : to
        uo      : uo
        vo      : vo
        woce    : wo
        woce_eiv: wo_e
        avt_evd : k_evd
        ttrd: ttrd*
        strd: strd*
        ketrd: ketrd*


processing:
  domain_path: data/raw/EXP01
  dynamics: false
  exp_in: EXP01_rest6m2000_1
  exp_out: EXP01
  exp_out_suffix: _rest6m2000_1
  n_chunks: 10
  nemo_path: data/raw/EXP01
  time_start: 0
  time_stop: 4100
    