preprocessing:
  prioritize_existing: true
processing:
  dynamics: false
  exp_in: EXP00_rest6m2000
  exp_out: EXP00
  exp_out_suffix: _rest6m2000
  n_chunks: 10
  nemo_path: 'data/raw/EXP00'
  domain_path: 'data/raw/EXP00'
  time_start: 0
  time_stop: 4100
